export const traducao = {
  happy: 'FELIZ',
  sad: 'TRISTE',
  terrible: 'ACABADO',
  ok: 'OK',
  radiant: 'RADIANTE',
  sports: 'esporte',
  shopping: 'compras',
  rest: 'descanso',
  party: 'festa',
  movies: 'filmes e séries',
  good_meal: 'boa refeição',
  games: 'jogos',
  date: 'encontro',
  cooking: 'cozinhar',
  male: 'MASCULINO',
  female: 'FEMININO',
};
